### ISSUE TITLE
[B] Wrong enum default for map picker

### ISSUE THREAD

**Issue by schroef** [s-leger/sun_position#3]
In ui_sun.py the picking of the map size has been reduced to None or the Biggest version. Yet for the Enum default the value is set to "2". The Enum only has 2 items, so this should be "1", the default for the map.

See ui_sun.py > #669

![screen shot 2018-03-06 at 9 23 40 am](https://user-images.githubusercontent.com/6923008/37034576-189d1474-2120-11e8-805c-996c34146a8e.png)

**Comment by s-leger** [comment]
Thank for report.

Fixed in source.
